import { Domain, DomainVerificationStatus } from '@/interfaces';

const fakeDomains: Domain[] = [
  {
    id: '1',
    workspaceId: '0',
    host: 'polysharp.fr',
    verificationKey: 'sinatra-site-verification=abcde',
    verificationStatus: DomainVerificationStatus.VERIFIED,
    verifiedAt: new Date('2023-11-01'),
    updatedAt: new Date(),
    createdAt: new Date('2023-10-25'),
  },
  {
    id: '2',
    workspaceId: '0',
    host: 'example-workspace0.com',
    verificationKey: 'sinatra-site-verification=klmno',
    verificationStatus: DomainVerificationStatus.VERIFIED,
    verifiedAt: new Date('2023-11-15'),
    updatedAt: new Date(),
    createdAt: new Date('2023-11-10'),
  },
  {
    id: '3',
    workspaceId: '0',
    host: 'test-verified0.net',
    verificationKey: 'sinatra-site-verification=verifiedkey0',
    verificationStatus: DomainVerificationStatus.VERIFIED,
    verifiedAt: new Date('2023-11-20'),
    updatedAt: new Date(),
    createdAt: new Date('2023-11-18'),
  },
  {
    id: '4',
    workspaceId: '0',
    host: 'pending-domain0.org',
    verificationKey: 'sinatra-site-verification=pending0',
    verificationStatus: DomainVerificationStatus.PENDING,
    verifiedAt: null,
    updatedAt: new Date(),
    createdAt: new Date('2023-11-19'),
  },
  {
    id: '5',
    workspaceId: '0',
    host: 'failed-domain0.com',
    verificationKey: 'sinatra-site-verification=failed0',
    verificationStatus: DomainVerificationStatus.FAILED,
    verifiedAt: null,
    updatedAt: new Date(),
    createdAt: new Date('2023-11-15'),
  },
  {
    id: '6',
    workspaceId: '1',
    host: 'yopta.life',
    verificationKey: 'sinatra-site-verification=fghij',
    verificationStatus: DomainVerificationStatus.VERIFIED,
    verifiedAt: new Date('2023-11-01'),
    updatedAt: new Date(),
    createdAt: new Date('2023-10-25'),
  },
  {
    id: '7',
    workspaceId: '1',
    host: 'workspace1-verified.com',
    verificationKey: 'sinatra-site-verification=verifiedkey1',
    verificationStatus: DomainVerificationStatus.VERIFIED,
    verifiedAt: new Date('2023-11-10'),
    updatedAt: new Date(),
    createdAt: new Date('2023-11-08'),
  },
  {
    id: '8',
    workspaceId: '1',
    host: 'test-verified1.net',
    verificationKey: 'sinatra-site-verification=verifiedkey1-test',
    verificationStatus: DomainVerificationStatus.VERIFIED,
    verifiedAt: new Date('2023-11-18'),
    updatedAt: new Date(),
    createdAt: new Date('2023-11-15'),
  },
  {
    id: '9',
    workspaceId: '1',
    host: 'pending-domain1.org',
    verificationKey: 'sinatra-site-verification=pending1',
    verificationStatus: DomainVerificationStatus.PENDING,
    verifiedAt: null,
    updatedAt: new Date(),
    createdAt: new Date('2023-11-19'),
  },
  {
    id: '10',
    workspaceId: '1',
    host: 'failed-domain1.com',
    verificationKey: 'sinatra-site-verification=failed1',
    verificationStatus: DomainVerificationStatus.FAILED,
    verifiedAt: null,
    updatedAt: new Date(),
    createdAt: new Date('2023-11-12'),
  },
];

export async function getDomains(workspaceId: string): Promise<Domain[]> {
  return Promise.resolve<Domain[]>(
    fakeDomains.filter((v) => `${v.workspaceId}` === workspaceId),
  );
}
